---
services:
  api:
    build:
      context: ./api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3000
    environment:
      TZ: Asia/Seoul
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ai-invest-assistant
      DB_PASSWORD: ai-invest-assistant
      DB_DATABASE: ai-invest-assistant
    volumes:
      - ./api/src:/app/src

  ui:
    build:
      context: ./ui
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Seoul
      NODE_ENV: development
      API_URL: http://api:3000/
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public

  db:
    image: mariadb:11.5.2
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      TZ: Asia/Seoul
      MARIADB_USER: ai-invest-assistant
      MARIADB_ROOT_PASSWORD: ai-invest-assistant
      MARIADB_PASSWORD: ai-invest-assistant
      MARIADB_DATABASE: ai-invest-assistant
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
