---
version: "3.8"

services:
  api:
    build:
      context: ./api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development

  ui:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
