---
mariadb:
  enabled: true
  primary:
    service:
      type: LoadBalancer

api:
  image:
    pullPolicy: Never
    tag: latest
  volumes:
    - name: src
      hostPath:
        path: /app/api/src
  volumeMounts:
    - name: src
      mountPath: /app/src
  autoscaling:
    enabled: true
    minReplicas: 2
  service:
    type: LoadBalancer
    port: 3001
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
  aws:
    region: ap-northeast-2
    sqs:
      queueUrl: https://sqs.ap-northeast-2.amazonaws.com/889753608001/kkalla-dev-sqs

ui:
  image:
    pullPolicy: Never
    tag: latest
  volumes:
    - name: src
      hostPath:
        path: /app/ui/src
    - name: public
      hostPath:
        path: /app/ui/public
  volumeMounts:
    - name: src
      mountPath: /app/src
    - name: public
      mountPath: /app/public
  autoscaling:
    enabled: false
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
  publicUrl: http://localhost:3000/
  api:
    url: "http://{{ .Release.Name }}-api.{{ .Release.Namespace }}.svc.cluster.local:3001/"
