---
mariadb:
  enabled: true

ui:
  ingress:
    enabled: true
    hosts:
      - host: ai.copy-money.com
        paths:
          - path: /
            pathType: ImplementationSpecific
  publicUrl: http://ai.copy-money.com/
