---
mariadb:
  enabled: true

api:
  autoscaling:
    enabled: false
  aws:
    region: ap-northeast-2
    sqs:
      queueUrl: https://sqs.ap-northeast-2.amazonaws.com/889753608001/kkalla-prd-sqs

ui:
  autoscaling:
    enabled: false
  publicUrl: http://localhost/
  ingress:
    enabled: true
    hosts:
      - paths:
          - path: /
            pathType: ImplementationSpecific
