---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.fullname" . }}
data:
  TZ: "Asia/Seoul"
  NEXTAUTH_URL: {{ .Values.publicUrl | quote }}
  API_URL: {{ tpl .Values.api.url . | quote }}
