---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ui.fullname" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  NEXTAUTH_SECRET: {{ include "ui.auth.secret" . | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.auth.google.id | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.auth.google.secret | b64enc | quote }}
