---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ui.fullname" . }}
type: Opaque
data:
  auth-secret: {{ include "ui.auth.secret" . }}
  auth-google-id: {{ .Values.auth.google.id | b64enc }}
  auth-google-secret: {{ .Values.auth.google.secret | b64enc }}
