---
mariadb:
  enabled: true
  auth:
    database: kkalla
    username: kkalla
  primary:
    service:
      type: ClusterIP
      ports:
        mysql: 3306
    extraEnvVars:
      - name: TZ
        value: Asia/Seoul

api:
  db:
    host: "{{ .Release.Name }}-mariadb.{{ .Release.Namespace }}.svc.cluster.local"
    port: 3306
    database: kkalla
    username: kkalla
  redis:
    host: "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local"
    port: 6379

ui:
  api:
    url: "http://{{ .Release.Name }}-api.{{ .Release.Namespace }}.svc.cluster.local:3000/"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
  master:
    service:
      type: ClusterIP
      ports:
        redis: 6379
    extraEnvVars:
      - name: TZ
        value: Asia/Seoul
