---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
data:
  TZ: "Asia/Seoul"
  TZ_OFFSET: "+09:00"
  DB_HOST: "{{ tpl .Values.db.host . }}"
  DB_PORT: "{{ .Values.db.port }}"
  DB_DATABASE: "{{ .Values.db.database }}"
  DB_USER: "{{ .Values.db.username }}"
  OPENAI_SECRET_KEY: "{{ .Values.openai.secretKey }}"
  UPBIT_ACCESS_KEY: "{{ .Values.upbit.accessKey }}"
  UPBIT_SECRET_KEY: "{{ .Values.upbit.secretKey }}"
  TEST_EMAIL: "{{ .Values.test.email }}"
