---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
type: Opaque
data:
  auth-google-id: {{ .Values.auth.google.id | b64enc }}
  auth-google-secret: {{ .Values.auth.google.secret | b64enc }}
  db-password: {{ .Values.db.password | b64enc }}
  db-secret: {{ include "db.secret" . }}
