---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: latest

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Setup Helm secrets
        run: |
          cat > secrets.yaml << 'EOL'
          ---
          auth:
            db: &db
              password: ${{ secrets.DB_PASSWORD }}
              rootPassword: ${{ secrets.DB_ROOT_PASSWORD }}
            google: &google
              id: ${{ secrets.GOOGLE_CLIENT_ID }}
              secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}

          mariadb:
            auth: *db
          api:
            db: *db
            auth:
              google: *google
          ui:
            publicUrl: ${{ vars.PUBLIC_URL }}
            auth:
              google: *google
          EOL

      - name: Deploy Helm chart
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ vars.EC2_HOST }}
          EC2_USER: ${{ vars.EC2_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          make install ENV=production
