---
name: Lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - api
          - ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
          cache: npm

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: npm install

      - name: Run lint
        working-directory: ${{ matrix.project }}
        run: npm run lint
