---
name: Release

on:
  push:
    branches:
      - release/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Versioning
        id: version
        run: |
          echo "version=$(cat version)" >> $GITHUB_OUTPUT

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            ./api/node_modules
            ./ui/node_modules
            ./ui/.next/cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build and push
        uses: docker/bake-action@v5
        with:
          push: true
          set: |
            *.BUILD_TARGET=development
            *.IMAGE_REGISTRY=ghcr.io/eunsoogi
            *.IMAGE_NAME_PREFIX=kkalla
            *.IMAGE_TAG=${{ steps.version.outputs.version }}

      - name: Export API cache
        uses: docker/build-push-action@v6
        with:
          context: ./api
          target: cache
          outputs: |
            type=local,src=/app/node_modules,dest=./ui/node_modules

      - name: Export UI cache
        uses: docker/build-push-action@v6
        with:
          context: ./ui
          target: cache
          outputs: |
            type=local,src=/app/node_modules,dest=./ui/node_modules
            type=local,src=/app/.next/cache,dest=./ui/.next/cache

  release:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Versioning
        id: version
        run: |
          echo "version=$(cat version)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
