---
name: Release

on:
  push:
    branches:
      - release/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Versioning
        id: version
        run: |
          echo "version=$(cat version)" >> $GITHUB_OUTPUT

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/api/node_modules
            ${{ github.workspace }}/ui/node_modules
            ${{ github.workspace }}/ui/.next/cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Make build cache directories
        run: |
          mkdir -p ${{ github.workspace }}/api/node_modules
          mkdir -p ${{ github.workspace }}/ui/node_modules
          mkdir -p ${{ github.workspace }}/ui/.next/cache

      - name: Build and push
        uses: docker/bake-action@v5
        env:
          BUILD_TARGET: production
          IMAGE_REGISTRY: ghcr.io/eunsoogi
          IMAGE_NAME_PREFIX: kkalla
          IMAGE_TAG: ${{ steps.version.outputs.version }}
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Export API cache
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ github.workspace }}/api
          target: cache
          cache-from: type=gha
          outputs: |
            type=local,dest=${{ github.workspace }}/api

      - name: Export UI cache
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ github.workspace }}/ui
          target: cache
          cache-from: type=gha
          outputs: |
            type=local,dest=${{ github.workspace }}/ui

  release:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Versioning
        id: version
        run: |
          echo "version=$(cat version)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
